package menu;

import ventas.FrameVentas;
import empresas.FrameEmpresas;

public class MainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());
    private static final long serialVersionUID = 1L;

    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVentas = new javax.swing.JButton();
        buttonCredits = new javax.swing.JButton();
        buttonClientes = new javax.swing.JButton();
        buttonEmpresas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gnuino Systems Demo v0.1");

        buttonVentas.setText("Ventas");
        buttonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVentasActionPerformed(evt);
            }
        });

        buttonCredits.setText("Credits");
        buttonCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreditsActionPerformed(evt);
            }
        });

        buttonClientes.setText("Clientes");
        buttonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientesActionPerformed(evt);
            }
        });

        buttonEmpresas.setText("Empresas");
        buttonEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmpresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonClientes, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(buttonVentas, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCredits, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEmpresas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(buttonCredits)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreditsActionPerformed
        // TODO add your handling code here:
        try(CreditsDialog c = new CreditsDialog(this, true);) {
            c.setVisible(true);
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_buttonCreditsActionPerformed

    private void buttonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientesActionPerformed
        try(JDialogModal d = new JDialogModal(this, true)) {
            d.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_buttonClientesActionPerformed

    private void buttonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVentasActionPerformed
        try(FrameVentas fventas = new FrameVentas(this, true)) {
            fventas.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_buttonVentasActionPerformed

    private void buttonEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmpresasActionPerformed
        try (FrameEmpresas fempresas = new FrameEmpresas(this, true)) {
            fempresas.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_buttonEmpresasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClientes;
    private javax.swing.JButton buttonCredits;
    private javax.swing.JButton buttonEmpresas;
    private javax.swing.JButton buttonVentas;
    // End of variables declaration//GEN-END:variables
}
